### ISSUE TITLE
Hang after loading menuloader.pxe

### ISSUE THREAD

**Issue by Sprbb** [nielsbasjes/ipxe-boot-rom#1]
Hi Niels,

At first thank you for your WONDERFUL contribution !!!

I made use of the possibility to build te the menuloader.pxe with all options enabled.
After that I was trying to load my own menu.ipxe from the 
webserver. Unfortunately it hangs. What is the best way to proceed ?

http://nl.tinypic.com/r/qqoj7c/9.

Kind regards,
Bas

**Comment by nielsbasjes** [comment]
I really don't know.
Ways I would proceed is looking if there are debug flags available and set those. In addition I would look at the logging of the  webserver (what does it retrieve), dhcp (does it get an ip) etc.
For these types of questions I suggest you go to the ipxe forum, the people there will be able to help you a lot better than I can.
